---
- name: Listen for events on a webhook
  hosts: all

  ## Define our source for events

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 50000

  ## Define the conditions we are looking for

  rules:
    - name: Say Hello
      condition: event.payload.message == "Ansible is super cool!"
      ## Define the action we should take should the condition be met
      action:
#        run_playbook:
#          name: say-what-playbook.yml
      debug:
        msg: "You said, '{{ event.payload.message }}'. Is it me you're looking for?"          
