---
- name: Listen for events on a webhook
  hosts: all

  ## Define our source for events

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 50000

  ## Define the conditions we are looking for

  rules:
    - name: What you said?
      condition: event.payload.message == "Ansible is super cool!"
      ## Define the action we should take should the condition be met
      action:
        debug:
          msg: "You said, '{{ event.payload.message }}'. Is it me you're looking for?"          
